// GENERATED by tools/gen_sp_builtins.py - do not edit; rerun `python tools/gen_sp_builtins.py`.
// Client-side SP builtins that neither BO1Zombies nor an SP lane table (src/game_sp/scr_sp_tables.h)
// provides: 0 functions, 0 methods. Each one raises a labelled script error when called, so
// scripts that reference it compile. Searched last. Porting one: add it to a lane table, rerun the
// generator (or list it in tools/sp_builtins_ported.txt).
#include <game_sp/scr_sp_tables.h>
#include <clientscript/cscr_vm.h>


const BuiltinFunctionDef g_csp_notported_functions[] =
{
    { nullptr, nullptr, 0 } // end marker, keep last
};
const unsigned int g_csp_notported_function_count = ARRAY_COUNT(g_csp_notported_functions) - 1;

const BuiltinMethodDef g_csp_notported_methods[] =
{
    { nullptr, nullptr, 0 } // end marker, keep last
};
const unsigned int g_csp_notported_method_count = ARRAY_COUNT(g_csp_notported_methods) - 1;
