// GENERATED by tools/gen_sp_builtins.py - do not edit; rerun `python tools/gen_sp_builtins.py`.
// Server-side SP builtins that neither BO1Zombies nor an SP lane table (src/game_sp/scr_sp_tables.h)
// provides: 33 functions, 20 methods. Each one raises a labelled script error when called, so
// scripts that reference it compile. Searched last. Porting one: add it to a lane table, rerun the
// generator (or list it in tools/sp_builtins_ported.txt).
#include "scr_sp_tables.h"
#include <clientscript/cscr_vm.h>

static void __cdecl GScr_SpNotPorted_f_addnodetocurve() { Scr_Error(SCRIPTINSTANCE_SERVER, "addnodetocurve: not ported (SP 0x007f8070, function)", false); }
static void __cdecl GScr_SpNotPorted_f_anglelerp() { Scr_Error(SCRIPTINSTANCE_SERVER, "anglelerp: not ported (SP 0x007f9ab0, function)", false); }
static void __cdecl GScr_SpNotPorted_m_attachtodec20terminal(scr_entref_t) { Scr_Error(SCRIPTINSTANCE_SERVER, "attachtodec20terminal: not ported (SP 0x007d7690, method)", false); }
static void __cdecl GScr_SpNotPorted_f_badplace_delete() { Scr_Error(SCRIPTINSTANCE_SERVER, "badplace_delete: not ported (SP 0x00800010, function)", false); }
static void __cdecl GScr_SpNotPorted_f_buildcurve() { Scr_Error(SCRIPTINSTANCE_SERVER, "buildcurve: not ported (SP 0x007f80e0, function)", false); }
static void __cdecl GScr_SpNotPorted_f_bullettracer() { Scr_Error(SCRIPTINSTANCE_SERVER, "bullettracer: not ported (SP 0x00682430, function)", false); }
static void __cdecl GScr_SpNotPorted_f_canspawnturret() { Scr_Error(SCRIPTINSTANCE_SERVER, "canspawnturret: not ported (SP 0x007f1940, function)", false); }
static void __cdecl GScr_SpNotPorted_m_checkcoverexitposwithpath(scr_entref_t) { Scr_Error(SCRIPTINSTANCE_SERVER, "checkcoverexitposwithpath: not ported (SP 0x007c9ae0, method)", false); }
static void __cdecl GScr_SpNotPorted_f_commitsave() { Scr_Error(SCRIPTINSTANCE_SERVER, "commitsave: not ported (SP 0x007fb040, function)", false); }
static void __cdecl GScr_SpNotPorted_m_detachdec20terminal(scr_entref_t) { Scr_Error(SCRIPTINSTANCE_SERVER, "detachdec20terminal: not ported (SP 0x007d7700, method)", false); }
static void __cdecl GScr_SpNotPorted_m_forcetexturestoload(scr_entref_t) { Scr_Error(SCRIPTINSTANCE_SERVER, "forcetexturestoload: not ported (SP 0x00651a30, method)", false); }
static void __cdecl GScr_SpNotPorted_f_freecurve() { Scr_Error(SCRIPTINSTANCE_SERVER, "freecurve: not ported (SP 0x007f8050, function)", false); }
static void __cdecl GScr_SpNotPorted_f_getcurve() { Scr_Error(SCRIPTINSTANCE_SERVER, "getcurve: not ported (SP 0x007f8030, function)", false); }
static void __cdecl GScr_SpNotPorted_f_getdate() { Scr_Error(SCRIPTINSTANCE_SERVER, "getdate: not ported (SP 0x00804120, function)", false); }
static void __cdecl GScr_SpNotPorted_m_getdebugeye(scr_entref_t) { Scr_Error(SCRIPTINSTANCE_SERVER, "getdebugeye: not ported (SP 0x007f4310, method)", false); }
static void __cdecl GScr_SpNotPorted_f_getdumpcmdsfortimedelta() { Scr_Error(SCRIPTINSTANCE_SERVER, "getdumpcmdsfortimedelta: not ported (SP 0x007f1140, function)", false); }
static void __cdecl GScr_SpNotPorted_f_getspawnerteamarray() { Scr_Error(SCRIPTINSTANCE_SERVER, "getspawnerteamarray: not ported (SP 0x007f0df0, function)", false); }
static void __cdecl GScr_SpNotPorted_f_gettimescale() { Scr_Error(SCRIPTINSTANCE_SERVER, "gettimescale: not ported (SP 0x007f26d0, function)", false); }
static void __cdecl GScr_SpNotPorted_m_givegamerpicture(scr_entref_t) { Scr_Error(SCRIPTINSTANCE_SERVER, "givegamerpicture: not ported (SP 0x00651a30, method)", false); }
static void __cdecl GScr_SpNotPorted_m_haspath(scr_entref_t) { Scr_Error(SCRIPTINSTANCE_SERVER, "haspath: not ported (SP 0x00802ad0, method)", false); }
static void __cdecl GScr_SpNotPorted_m_initdec20terminal(scr_entref_t) { Scr_Error(SCRIPTINSTANCE_SERVER, "initdec20terminal: not ported (SP 0x007d7630, method)", false); }
static void __cdecl GScr_SpNotPorted_f_issavesuccessful() { Scr_Error(SCRIPTINSTANCE_SERVER, "issavesuccessful: not ported (SP 0x007faff0, function)", false); }
static void __cdecl GScr_SpNotPorted_m_itemweaponsetoptions(scr_entref_t) { Scr_Error(SCRIPTINSTANCE_SERVER, "itemweaponsetoptions: not ported (SP 0x007f3b50, method)", false); }
static void __cdecl GScr_SpNotPorted_m_magicgrenade(scr_entref_t) { Scr_Error(SCRIPTINSTANCE_SERVER, "magicgrenade: not ported (SP 0x007f3bd0, method)", false); }
static void __cdecl GScr_SpNotPorted_m_pickupgrenade(scr_entref_t) { Scr_Error(SCRIPTINSTANCE_SERVER, "pickupgrenade: not ported (SP 0x007cc380, method)", false); }
static void __cdecl GScr_SpNotPorted_f_prefetchlevel() { Scr_Error(SCRIPTINSTANCE_SERVER, "prefetchlevel: not ported (SP 0x00651a30, function)", false); }
static void __cdecl GScr_SpNotPorted_f_preventmipsfromloading() { Scr_Error(SCRIPTINSTANCE_SERVER, "preventmipsfromloading: not ported (SP 0x00651a30, function)", false); }
static void __cdecl GScr_SpNotPorted_f_record3dtext() { Scr_Error(SCRIPTINSTANCE_SERVER, "record3dtext: not ported (SP 0x00651a30, function)", false); }
static void __cdecl GScr_SpNotPorted_f_recordent() { Scr_Error(SCRIPTINSTANCE_SERVER, "recordent: not ported (SP 0x00651a30, function)", false); }
static void __cdecl GScr_SpNotPorted_f_recordenttext() { Scr_Error(SCRIPTINSTANCE_SERVER, "recordenttext: not ported (SP 0x00651a30, function)", false); }
static void __cdecl GScr_SpNotPorted_f_recordline() { Scr_Error(SCRIPTINSTANCE_SERVER, "recordline: not ported (SP 0x00651a30, function)", false); }
static void __cdecl GScr_SpNotPorted_f_savegamenocommit() { Scr_Error(SCRIPTINSTANCE_SERVER, "savegamenocommit: not ported (SP 0x007fae80, function)", false); }
static void __cdecl GScr_SpNotPorted_m_setanimknoblimitedrestart(scr_entref_t) { Scr_Error(SCRIPTINSTANCE_SERVER, "setanimknoblimitedrestart: not ported (SP 0x00800d20, method)", false); }
static void __cdecl GScr_SpNotPorted_f_setcollectible() { Scr_Error(SCRIPTINSTANCE_SERVER, "setcollectible: not ported (SP 0x00804a60, function)", false); }
static void __cdecl GScr_SpNotPorted_f_setcurvenotifyent() { Scr_Error(SCRIPTINSTANCE_SERVER, "setcurvenotifyent: not ported (SP 0x007f7ec0, function)", false); }
static void __cdecl GScr_SpNotPorted_f_setdebugangles() { Scr_Error(SCRIPTINSTANCE_SERVER, "setdebugangles: not ported (SP 0x00803da0, function)", false); }
static void __cdecl GScr_SpNotPorted_f_setdebugorigin() { Scr_Error(SCRIPTINSTANCE_SERVER, "setdebugorigin: not ported (SP 0x00803d80, function)", false); }
static void __cdecl GScr_SpNotPorted_m_setflaggedanimknoblimitedrestart(scr_entref_t) { Scr_Error(SCRIPTINSTANCE_SERVER, "setflaggedanimknoblimitedrestart: not ported (SP 0x00801d50, method)", false); }
static void __cdecl GScr_SpNotPorted_m_setlookattext(scr_entref_t) { Scr_Error(SCRIPTINSTANCE_SERVER, "setlookattext: not ported (SP 0x0048cd50, method)", false); }
static void __cdecl GScr_SpNotPorted_m_setsoundblend(scr_entref_t) { Scr_Error(SCRIPTINSTANCE_SERVER, "setsoundblend: not ported (SP 0x00651a30, method)", false); }
static void __cdecl GScr_SpNotPorted_m_setturretanim(scr_entref_t) { Scr_Error(SCRIPTINSTANCE_SERVER, "setturretanim: not ported (SP 0x007ccc20, method)", false); }
static void __cdecl GScr_SpNotPorted_f_setuinextlevel() { Scr_Error(SCRIPTINSTANCE_SERVER, "setuinextlevel: not ported (SP 0x00651a30, function)", false); }
static void __cdecl GScr_SpNotPorted_m_shoot(scr_entref_t) { Scr_Error(SCRIPTINSTANCE_SERVER, "shoot: not ported (SP 0x007c9b50, method)", false); }
static void __cdecl GScr_SpNotPorted_f_splitviewallowed() { Scr_Error(SCRIPTINSTANCE_SERVER, "splitviewallowed: not ported (SP 0x00651a30, function)", false); }
static void __cdecl GScr_SpNotPorted_f_startcurve() { Scr_Error(SCRIPTINSTANCE_SERVER, "startcurve: not ported (SP 0x007f7f50, function)", false); }
static void __cdecl GScr_SpNotPorted_f_startmultiplayergame() { Scr_Error(SCRIPTINSTANCE_SERVER, "startmultiplayergame: not ported (SP 0x008052d0, function)", false); }
static void __cdecl GScr_SpNotPorted_m_stopuseanimtree(scr_entref_t) { Scr_Error(SCRIPTINSTANCE_SERVER, "stopuseanimtree: not ported (SP 0x00808800, method)", false); }
static void __cdecl GScr_SpNotPorted_f_threatbiasgroupexists() { Scr_Error(SCRIPTINSTANCE_SERVER, "threatbiasgroupexists: not ported (SP 0x008192d0, function)", false); }
static void __cdecl GScr_SpNotPorted_m_ufomode(scr_entref_t) { Scr_Error(SCRIPTINSTANCE_SERVER, "ufomode: not ported (SP 0x007f1210, method)", false); }
static void __cdecl GScr_SpNotPorted_f_updategamerprofile() { Scr_Error(SCRIPTINSTANCE_SERVER, "updategamerprofile: not ported (SP 0x00651a30, function)", false); }
static void __cdecl GScr_SpNotPorted_m_updateprone(scr_entref_t) { Scr_Error(SCRIPTINSTANCE_SERVER, "updateprone: not ported (SP 0x007ca820, method)", false); }
static void __cdecl GScr_SpNotPorted_f_weapondogibbing() { Scr_Error(SCRIPTINSTANCE_SERVER, "weapondogibbing: not ported (SP 0x007fc320, function)", false); }
static void __cdecl GScr_SpNotPorted_f_weaponmaxgibdistance() { Scr_Error(SCRIPTINSTANCE_SERVER, "weaponmaxgibdistance: not ported (SP 0x007fc360, function)", false); }

const BuiltinFunctionDef g_sp_notported_functions[] =
{
    { "addnodetocurve", GScr_SpNotPorted_f_addnodetocurve, 0 }, // SP front end script (tools/sp_frontend_builtins.txt)
    { "anglelerp", GScr_SpNotPorted_f_anglelerp, 0 }, // SP front end script (tools/sp_frontend_builtins.txt)
    { "badplace_delete", GScr_SpNotPorted_f_badplace_delete, 0 }, // SP front end script (tools/sp_frontend_builtins.txt)
    { "buildcurve", GScr_SpNotPorted_f_buildcurve, 0 }, // SP front end script (tools/sp_frontend_builtins.txt)
    { "bullettracer", GScr_SpNotPorted_f_bullettracer, 0 }, // SP front end script (tools/sp_frontend_builtins.txt)
    { "canspawnturret", GScr_SpNotPorted_f_canspawnturret, 0 }, // SP front end script (tools/sp_frontend_builtins.txt)
    { "commitsave", GScr_SpNotPorted_f_commitsave, 0 }, // referenced
    { "freecurve", GScr_SpNotPorted_f_freecurve, 0 }, // SP front end script (tools/sp_frontend_builtins.txt)
    { "getcurve", GScr_SpNotPorted_f_getcurve, 0 }, // SP front end script (tools/sp_frontend_builtins.txt)
    { "getdate", GScr_SpNotPorted_f_getdate, 1 }, // developer-only (retail compile drops the call)
    { "getdumpcmdsfortimedelta", GScr_SpNotPorted_f_getdumpcmdsfortimedelta, 1 }, // developer-only (retail compile drops the call)
    { "getspawnerteamarray", GScr_SpNotPorted_f_getspawnerteamarray, 0 }, // SP front end script (tools/sp_frontend_builtins.txt)
    { "gettimescale", GScr_SpNotPorted_f_gettimescale, 0 }, // SP front end script (tools/sp_frontend_builtins.txt)
    { "issavesuccessful", GScr_SpNotPorted_f_issavesuccessful, 0 }, // referenced
    { "prefetchlevel", GScr_SpNotPorted_f_prefetchlevel, 0 }, // shares the address of a referenced builtin
    { "preventmipsfromloading", GScr_SpNotPorted_f_preventmipsfromloading, 0 }, // shares the address of a referenced builtin
    { "record3dtext", GScr_SpNotPorted_f_record3dtext, 1 }, // shares the address of a referenced builtin
    { "recordent", GScr_SpNotPorted_f_recordent, 1 }, // shares the address of a referenced builtin
    { "recordenttext", GScr_SpNotPorted_f_recordenttext, 1 }, // shares the address of a referenced builtin
    { "recordline", GScr_SpNotPorted_f_recordline, 1 }, // shares the address of a referenced builtin
    { "savegamenocommit", GScr_SpNotPorted_f_savegamenocommit, 0 }, // referenced
    { "setcollectible", GScr_SpNotPorted_f_setcollectible, 0 }, // SP front end script (tools/sp_frontend_builtins.txt)
    { "setcurvenotifyent", GScr_SpNotPorted_f_setcurvenotifyent, 0 }, // SP front end script (tools/sp_frontend_builtins.txt)
    { "setdebugangles", GScr_SpNotPorted_f_setdebugangles, 1 }, // SP front end script (tools/sp_frontend_builtins.txt)
    { "setdebugorigin", GScr_SpNotPorted_f_setdebugorigin, 1 }, // SP front end script (tools/sp_frontend_builtins.txt)
    { "setuinextlevel", GScr_SpNotPorted_f_setuinextlevel, 0 }, // shares the address of a referenced builtin
    { "splitviewallowed", GScr_SpNotPorted_f_splitviewallowed, 0 }, // shares the address of a referenced builtin
    { "startcurve", GScr_SpNotPorted_f_startcurve, 0 }, // SP front end script (tools/sp_frontend_builtins.txt)
    { "startmultiplayergame", GScr_SpNotPorted_f_startmultiplayergame, 0 }, // SP front end script (tools/sp_frontend_builtins.txt)
    { "threatbiasgroupexists", GScr_SpNotPorted_f_threatbiasgroupexists, 0 }, // SP front end script (tools/sp_frontend_builtins.txt)
    { "updategamerprofile", GScr_SpNotPorted_f_updategamerprofile, 0 }, // shares the address of a referenced builtin
    { "weapondogibbing", GScr_SpNotPorted_f_weapondogibbing, 0 }, // SP front end script (tools/sp_frontend_builtins.txt)
    { "weaponmaxgibdistance", GScr_SpNotPorted_f_weaponmaxgibdistance, 0 }, // SP front end script (tools/sp_frontend_builtins.txt)
    { nullptr, nullptr, 0 } // end marker, keep last
};
const unsigned int g_sp_notported_function_count = ARRAY_COUNT(g_sp_notported_functions) - 1;

const BuiltinMethodDef g_sp_notported_methods[] =
{
    { "attachtodec20terminal", GScr_SpNotPorted_m_attachtodec20terminal, 0 }, // SP front end script (tools/sp_frontend_builtins.txt)
    { "checkcoverexitposwithpath", GScr_SpNotPorted_m_checkcoverexitposwithpath, 0 }, // SP front end script (tools/sp_frontend_builtins.txt)
    { "detachdec20terminal", GScr_SpNotPorted_m_detachdec20terminal, 0 }, // SP front end script (tools/sp_frontend_builtins.txt)
    { "forcetexturestoload", GScr_SpNotPorted_m_forcetexturestoload, 0 }, // shares the address of a referenced builtin
    { "getdebugeye", GScr_SpNotPorted_m_getdebugeye, 1 }, // SP front end script (tools/sp_frontend_builtins.txt)
    { "givegamerpicture", GScr_SpNotPorted_m_givegamerpicture, 0 }, // shares the address of a referenced builtin
    { "haspath", GScr_SpNotPorted_m_haspath, 0 }, // SP front end script (tools/sp_frontend_builtins.txt)
    { "initdec20terminal", GScr_SpNotPorted_m_initdec20terminal, 0 }, // SP front end script (tools/sp_frontend_builtins.txt)
    { "itemweaponsetoptions", GScr_SpNotPorted_m_itemweaponsetoptions, 0 }, // SP front end script (tools/sp_frontend_builtins.txt)
    { "magicgrenade", GScr_SpNotPorted_m_magicgrenade, 0 }, // referenced
    { "pickupgrenade", GScr_SpNotPorted_m_pickupgrenade, 0 }, // SP front end script (tools/sp_frontend_builtins.txt)
    { "setanimknoblimitedrestart", GScr_SpNotPorted_m_setanimknoblimitedrestart, 0 }, // SP front end script (tools/sp_frontend_builtins.txt)
    { "setflaggedanimknoblimitedrestart", GScr_SpNotPorted_m_setflaggedanimknoblimitedrestart, 0 }, // SP front end script (tools/sp_frontend_builtins.txt)
    { "setlookattext", GScr_SpNotPorted_m_setlookattext, 0 }, // SP front end script (tools/sp_frontend_builtins.txt)
    { "setsoundblend", GScr_SpNotPorted_m_setsoundblend, 0 }, // shares the address of a referenced builtin
    { "setturretanim", GScr_SpNotPorted_m_setturretanim, 0 }, // SP front end script (tools/sp_frontend_builtins.txt)
    { "shoot", GScr_SpNotPorted_m_shoot, 0 }, // referenced
    { "stopuseanimtree", GScr_SpNotPorted_m_stopuseanimtree, 0 }, // SP front end script (tools/sp_frontend_builtins.txt)
    { "ufomode", GScr_SpNotPorted_m_ufomode, 1 }, // developer-only (retail compile drops the call)
    { "updateprone", GScr_SpNotPorted_m_updateprone, 0 }, // referenced
    { nullptr, nullptr, 0 } // end marker, keep last
};
const unsigned int g_sp_notported_method_count = ARRAY_COUNT(g_sp_notported_methods) - 1;
